### ISSUE TITLE
PlatformException (PlatformException(error, Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null))

### ISSUE THREAD

**Issue by asif4483** [jamalag/flutter-webrtc-part2#3]
![error](https://user-images.githubusercontent.com/24164393/93662653-501ba100-fa7f-11ea-9dbb-4cb462d1ca56.JPG)

**Comment by asif4483** [comment]
and also getting this error : "Unable to RTCPeerConnection::setRemoteDescription: Failed to set remote answer sdp: Called in wrong state: kStable"

**Comment by asif4483** [comment]
This issue is fixed.

**Comment by jamalag** [comment]
Would you please share the fix? because I know I have responded to this '...wrong state..' issue a few times in the YouTube comments. It is always because createOffer is called at least twice and it should be once per pc.
