### ISSUE TITLE
D/FlutterWebRTCPlugin( 6528): peerConnectionAddICECandidate() start || D/FlutterWebRTCPlugin( 6528): peerConnectionAddICECandidate() end

### ISSUE THREAD

**Issue by asif4483** [jamalag/flutter-webrtc-part2#4]
![image](https://user-images.githubusercontent.com/24164393/93664117-26b44280-fa8a-11ea-8398-5acefbb46d51.png)

**Comment by asif4483** [comment]
solved

**Comment by jamalag** [comment]
Not sure what the issue was but may be if you briefly explain the issue and how you solved it would probably help others. Thanks
