### ISSUE TITLE
 Unhandled Exception: Unable to RTCPeerConnection::createAnswer: Error (null)

### ISSUE THREAD

**Issue by ctkqiang** [jamalag/flutter-webrtc-part2#5]
I was running your code, and I come into these error. I wonder what is it ?

```
2020-09-22 16:54:56.539143+0800 Runner[603:86509] [VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: Unable to RTCPeerConnection::createAnswer: Error (null)
#0      RTCPeerConnection.createAnswer (package:flutter_webrtc/rtc_peerconnection.dart:237:7)
<asynchronous suspension>
#1      _CallerAppState._createAnswer (package:/main.dart:190:31)
#2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
#3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
#5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
#6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
#7      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:256:7)
#8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:158:27)
#9      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:224:20)
#10     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
#11     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
#12     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
#13     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
#14     _rootRunUnary (dart:async/zone.dart:1206:13)
#15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#17     _invoke1 (dart:ui/hooks.dart:267:10)
#18     _dispatchPointerDataPacket (dart:ui/hooks.dart:176:5)
```

**Comment by jamalag** [comment]
Hi John, did you try to follow the YouTube video tutorial or did you clone the repo? I am not 100% sure about this error but it could related to creating an answer at wrong state. What I noticed in such cases, it was mostly to do with useEffect - i.e. calling either createOffer or createAnswer more than once per peer connection.

**Comment by ctkqiang** [comment]
> Hi John, did you try to follow the YouTube video tutorial or did you clone the repo? I am not 100% sure about this error but it could related to creating an answer at wrong state. What I noticed in such cases, it was mostly to do with useEffect - i.e. calling either createOffer or createAnswer more than once per peer connection.

I clone your repo and run it android to ios (not the web), and this happened

**Comment by jamalag** [comment]
flutter-webrtc parts 1 and 2 are demonstrating how to manually exchange SDP and Candidates to establish a connection between 2 peers (pc's). Copying as is between the content in the TextField and the console _without_ parsing and as in the tutorial using json strings pauses a problem. This is probably the reason createAnswer is failing due to wrong SDP format.
